### ISSUE TITLE
Ctrl/CMD+F does not work in the `bitrise.yml` editor

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#100]
If the focus is inside the yml editor CMD/Ctrl+F (find) does nothing.

If you click outside of the yml editor and then CMD/Ctrl+F that works.

**Comment by dbreuer** [comment]
Fixed by Switch from ACE editor to Monaco editor #315

**Comment by viktorbenei** [comment]
Awesome, thanks @dbreuer ! 🎉
