### ISSUE TITLE
Open links in Step/Input/etc description on new tab

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#106]
Right now if you click a link in a step's description that'll try to open the link in the same window/tab, which means that if you have any unsaved changes you can't leave the page/open the link, unless you discard those changes.

Solution/fix idea: simply open these links on a new tab by default.

Workaround: right-click -> open in new tab OR CMD/Ctrl+Click the link to open it on a new tab.

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-4-released/1765
