### ISSUE TITLE
UX: when add new step right sidebar is open, that should slide above the "X" at top right

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#107]
It's quite a bit misleading right now that the X is not for the right sidebar, but it is for the whole editor; so when you click it that will close the whole editor, not just the sidebar.

Either hide it, or when the sidebar is active the X should only close the sidebar.

**Comment by erosdome** [comment]
an update has been released on the website: close button is hidden when add step sidebar is visible
