### ISSUE TITLE
Error opening workflow

### ISSUE THREAD

**Issue by bennybates** [bitrise-io/bitrise-workflow-editor#109]
Getting the following when opening Workflow for one of my apps. It doesn't allow me to switch to other tabs because it is trying to force me to save but can't save, presumably because of the ENV error.

![image](https://cloud.githubusercontent.com/assets/1596695/26007995/f5cb932a-3710-11e7-9db7-7dcaef9098e8.png)

**Comment by bennybates** [comment]
URL is https://www.bitrise.io/app/cfe2c5d376bcfb48

**Comment by viktorbenei** [comment]
Thanks for reporting @bennybates !

We'll fix this ASAP, in the meantime you can find a workaround here: http://devcenter.bitrise.io/troubleshooting/workflow-editor-doesnt-load/

In short, there's an API Endpoint with which you can download the `bitrise.yml`, fix it and then upload it back to bitrise.io

**Comment by viktorbenei** [comment]
@erosdome pls make sure that the `bitrise.yml` tab is accessible "no matter what"

**Comment by viktorbenei** [comment]
Fix implemented, should be deployed in ~10-20 mins

**Comment by bennybates** [comment]
Looks good, thanks!

**Comment by viktorbenei** [comment]
Glad to hear that, thanks for confirming! 😊

**Comment by erosdome** [comment]
fix is also released for the offline editor:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-2-released/1739
