### ISSUE TITLE
Clicking the App Name doesn't do anything

### ISSUE THREAD

**Issue by bennybates** [bitrise-io/bitrise-workflow-editor#110]
I would expect it to bring me back to the "Builds" page I think. Currently nothing happens.

![image](https://cloud.githubusercontent.com/assets/1596695/26008210/cc8cb2c2-3711-11e7-88bc-4d784be69e3b.png)

**Comment by viktorbenei** [comment]
Thanks for reporting @bennybates !

Duplicate of: https://github.com/bitrise-io/bitrise-workflow-editor/issues/105
