### ISSUE TITLE
Don't show type tags / categories if there's 0 step matching the filter

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#111]
E.g. iOS project type - "installer" tag

![screenshot from 2017-05-12 19-36-27](https://cloud.githubusercontent.com/assets/430618/26009736/66a6ec6e-374a-11e7-855a-28ebf013a6d9.png)

**Comment by erosdome** [comment]
updated:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-4-released/1765
