### ISSUE TITLE
Android Keystore: don't use password type for the input

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#114]
We talked about this many times, and fixed it on bitrise.io many times ;)

input type=password will make the browser to auto-fill the input with your login psw

additionally it'll also prompt you when you save it whether you want to update *your user password* for the site (bitrise.io in this case)

there's a separate input type for this, which behaves like a password field but won't be treated like a user login form

<img width="973" alt="screen shot 2017-05-12 at 22 35 52" src="https://cloud.githubusercontent.com/assets/430618/26016363/f5f84da8-3764-11e7-8e0e-c1acc1c226e4.png">

**Comment by erosdome** [comment]
no other input type exists unfortunately :/ added autocomplete="off", which seems to have fixed it
