### ISSUE TITLE
Wrong help link: "Learn more about this on our Devcenter!"

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#115]
The **Replace variables in input?** toggle's **Learn more about this on our Devcenter!** help text links to http://devcenter.bitrise.io/v1.0/docs/manage-your-bitrise-workflow#section-step-inputs which does not exist.

Should link to: http://devcenter.bitrise.io/getting-started/manage-your-bitrise-workflow/#environment-variable-replace-mode

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-2-released/1739
