### ISSUE TITLE
[bitrise.io] There are unsaved changes popup - it's **below** the editor, can't see it until you close the editor!!

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#116]
Shows up only after you discard the changes and close the editor.. Until that it's hidden below the editor.

![screenshot from 2017-05-13 08-45-49](https://cloud.githubusercontent.com/assets/430618/26023270/96038922-37b8-11e7-844e-40f36513c3a6.png)

**Comment by erosdome** [comment]
fixed, will be released in a few minutes:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-3-released/1743
