### ISSUE TITLE
Step version number select box uses alphabetical sorting instead of numerical

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#121]
As you can see on attached picture, e.g. 0.1.12 should be on the top.
![image](https://cloud.githubusercontent.com/assets/3340954/26082312/8d225572-39cf-11e7-9984-a6fa936d1383.png)

**Comment by viktorbenei** [comment]
Definitely annoying. Thanks for reporting @koral-- ! ;)

@erosdome schedule a fix!

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-3-released/1743
