### ISSUE TITLE
Don't show the "Replace variables in input?" option under the inputs

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#123]
Should be shown in Env Vars etc, only remove from under the inputs.

It seems this causes confusion, e.g. why it have to be turned off for Script steps (https://discuss.bitrise.io/t/possible-to-create-env-file-with-app-env-variables-values-inside/517/4?u=viktorbenei)

The steps define a good base value for is expand, if not then should be fixed, or it's still possible to change in bitrise.yml

Maybe keep the help text there, which points to the related docs with `bitrise.yml` example too, but don't allow toggling it from the UI

**Comment by erosdome** [comment]
@bloodrabbit wdyt?

**Comment by bloodrabbit** [comment]
Agreed, as this was the case at the last editor too, we should bring back the same UI from there.

**Comment by erosdome** [comment]
Section removed, will add a help texture ASAP.

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-4-released/1765

**Comment by erosdome** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/bitrise-io/bitrise-workflow-editor/issues/123](https://trello.com/c/ZN1oAqYf/1637-https-github-com-bitrise-io-bitrise-workflow-editor-issues-123)

**Comment by erosdome** [comment]
indication of "is expand" added:

https://discuss.bitrise.io/t/workflow-editor-v1-0-6-released/1843
