### ISSUE TITLE
Usability improvements and bugs

### ISSUE THREAD

**Issue by doomsayer13** [bitrise-io/bitrise-workflow-editor#124]
1. Couldn't discard step title changes:
![kepernyofoto 2017-05-16 - 11 13 03](https://cloud.githubusercontent.com/assets/8809762/26098937/9123983e-3a29-11e7-92f1-c4d5ae2105ff.png)
2. Hide close icon of wf editor over the progress while loading wf data
![kepernyofoto 2017-05-16 - 11 09 54](https://cloud.githubusercontent.com/assets/8809762/26099238/749d1482-3a2a-11e7-9c09-bcdc23c5a96c.png)
3. Couldn't find out what will be happen if I click on the icon(add title attribute to buttons):
![kepernyofoto 2017-05-16 - 11 15 49](https://cloud.githubusercontent.com/assets/8809762/26099434/f7da5dc8-3a2a-11e7-9afa-fbd2290a2e53.png)
4. How to close step selector menu if I changed my mind and I don't want to add a new step(I clicked on "close workflow editor" button):
![kepernyofoto 2017-05-16 - 11 34 08](https://cloud.githubusercontent.com/assets/8809762/26099786/205ce45e-3a2c-11e7-8f1c-27b7567e344a.png)
5. Change cursor to default on non-editable input fields(it's confusing):
![kepernyofoto 2017-05-16 - 11 40 12](https://cloud.githubusercontent.com/assets/8809762/26100059/101cee12-3a2d-11e7-8e09-af2347791f6f.png)
6. I clicked on wf selector then on RENAME, but I didn't clicked on "Ok" button, just chose an another wf, then I clicked again on selector:
![kepernyofoto 2017-05-16 - 11 48 31](https://cloud.githubusercontent.com/assets/8809762/26100372/fd1eaac0-3a2d-11e7-9512-73f27e18237c.png)
7. Maybe it would be great if there is a Download/Delete all buttons for code signing files.
8. Trigger map editor:
  a) if you want to rearrange the trigger items and you drop the selected item before it change its position in the list the item will be opened in edit mode.
  b) it's the same trigger item:
       ![kepernyofoto 2017-05-16 - 12 07 53](https://cloud.githubusercontent.com/assets/8809762/26101120/51a05e52-3a30-11e7-9fbc-448f465b7259.png)
  c) (it works with every trigger type) I clicked on "Add trigger button" then I clicked on another trigger type tab then on previously selected tab and it shows duplicated trigger items(Note: couldn't save the trigger map, I got a popup with error message: "_Error saving app config: Validation failed: App config validation Failed to get config (bitrise.yml) from base 64 data, err: Failed to parse bitrise config, error: duplicated trigger item found (tag: *)_"):    
       ![kepernyofoto 2017-05-16 - 12 13 49](https://cloud.githubusercontent.com/assets/8809762/26101349/26fff602-3a31-11e7-9ac2-44561624c60f.png)

**Comment by erosdome** [comment]
1. Not a major UX issue, whereas also displaying a cancel button would make the step header look cluttered
2. Fixed
3. Popovers added
4. Workflow editor popup's close button hidden when add step sidebar is displayed, to avoid confusion. Escape key or clicking outside of the sidebar closes it.
5. Done
6. Fixed
7. Good idea, we might add it later on.
8. Fixed
