### ISSUE TITLE
Popup / help in Add Step sidebar when hovering over the "verified" / "community" badges

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#125]
The icons are awesome but not self explanatory enough without a hover.

When you browse steps in the add step sidebar there is now hint/help when you hover over the icon, so you don't know what that means, unless you add the step and then hover over the icon.

**Comment by erosdome** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Workflow editor - Popup / help in Add Step sidebar when hovering over the "verified" / "community" badges](https://trello.com/c/VEVmet9a/1636-workflow-editor-popup-help-in-add-step-sidebar-when-hovering-over-the-verified-community-badges)

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
