### ISSUE TITLE
Unsaved changes generated by switching workflows

### ISSUE THREAD

**Issue by godrei** [bitrise-io/bitrise-workflow-editor#129]
When you open up the workflow editor on the website and switch between workflows and try to navigate to another tab, it shows `Unsaved changes` popup.

**Comment by erosdome** [comment]
Could you provide the bitrise.yml of the app?

**Comment by godrei** [comment]
sorry i can not find the bitrise.yml produced this issue and can not reproduce again... feel free to close this issue, i will create a new one, with more info, if this happens again.
