### ISSUE TITLE
Step Title: handle the same way (re:changes) as any other input/change

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#130]
Right now the title is only changes/saved if you click on the green :white_check_mark: icon.

If you just edit it, then switch to another step for example, and then switch back, your title change will disappear.

For comparison, every other input, e.g. a step input, is kept between changes, and saved when you hit Cmd+S

I'd suggest to do the same for step titles - as soon as you change it in the input that should change the value, no need to click on the :white_check_mark: icon

**Comment by erosdome** [comment]
updated:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-4-released/1765
