### ISSUE TITLE
Adding new step after deleting another one -> step will be added to the wrong place (order)

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#131]
E.g. start with a 4 step workflow, remove the first two steps and the last one, leaving only one step (the third originally).

Now try to add a new step before the one remaining step: it'll be added **after** the step. Try again, it'll still be added **after** the step.

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-4-released/1765
