### ISSUE TITLE
Github icon of git:: step points to https://www.bitrise.io instead of repo

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#132]
I mean this icon:
![image](https://cloud.githubusercontent.com/assets/3340954/26218222/865ed5fc-3c0a-11e7-8286-a69b25c4ec46.png)
It should be either inactive (for ssh URLs) or may be extracted from step specification (for HTTPS URLs).

**Comment by viktorbenei** [comment]
Good catch, thanks for reporting @koral-- !

@erosdome please schedule a fix! ;)

**Comment by erosdome** [comment]
From 1.0.5, no link to source code is displaying if it is not found in step specification, will be available shortly on the website too:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-5-released/1790
