### ISSUE TITLE
Stale step name input state

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#133]
Repro steps:
1. Start step name editing (eg. 1st Script on attached picture)
2. Click on another step

The title is still in edit mode and contains a value from the previous step. 

![image](https://cloud.githubusercontent.com/assets/3340954/26219055/a78246b2-3c0d-11e7-828a-5642c71c2a82.png)

**Comment by viktorbenei** [comment]
Most likely a regression of https://github.com/bitrise-io/bitrise-workflow-editor/issues/130

Thanks @koral-- for reporting!

@erosdome schedule a fix! ;)

**Comment by erosdome** [comment]
fixed in 1.0.5, will be available shortly on the website too:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-5-released/1790
