### ISSUE TITLE
Missing input validation in workflow rename

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#134]
When adding a new workflow, confirmation button is disabled if workflow name is empty or duplicated however, when renaming you can confirm pretty much anything.

![image](https://cloud.githubusercontent.com/assets/3340954/26226168/03f907c4-3c2b-11e7-8381-71d9f9d4bbc7.png)

**Comment by erosdome** [comment]
True, fixing it ASAP. Thanks for reporting :)

**Comment by erosdome** [comment]
fixed in 1.0.5, will be available shortly on the website too:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-5-released/1790
