### ISSUE TITLE
Adding env var: the key text "KEY" should only be a placeholder!

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#135]
Right now when you add a new env var, click into the KEY field, the text "KEY" will remain there. If I just copy paste a key or want to quickly specify one I have to first delete the KEY text first, and input or paste the actual key after that.

I'd suggest making the "KEY" text in the key field just a placeholder, the same way as the "Value" text is just a placeholder in the value input.

**Comment by erosdome** [comment]
updated:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-5-released/1790
