### ISSUE TITLE
Add Step sidebar - show the Description of the step when hovering over the step card (when the step card expands)?

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#139]
Right now only the summary is shown. There's no point in expanding the card if only the summary is presented, as those are designed to be short (~1 liner)!

I'd rather switch to presenting the description in expanded view (if description is specified for the step).

![step-list-description](https://cloud.githubusercontent.com/assets/430618/26256570/af4860a6-3cbd-11e7-8d51-bb1938ba2df6.jpg)

**Comment by erosdome** [comment]
@bloodrabbit wdyt? Viktor says that summaries are - despite of some steps - not supposed to be more than a oneliner. Keeping that in mind for when that would become true to more and more steps, we should use the description instead. It is very long sometimes, so major cropping of the text would occur though.

**Comment by bloodrabbit** [comment]
In this case we should shorten the summaries of steps that have too long ones, so it fits into the default step size and remove the expand on hover option.

**Comment by erosdome** [comment]
update released: keeping in mind that summaries will be shorter sometime in the future, steps now don't expand on hover.
