### ISSUE TITLE
Make it simple to add path:: and git:: steps - custom steps / steps not shared in the StepLib

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#140]
I think a simple "secondary" mode in the Add Step sidebar should be enough, asking for the git clone URL and branch/tag in case of a "git::" reference, or the local path in case of a "path::" ref.

**Comment by doomsayer13** [comment]
#165

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.

**Comment by IchordeDionysos** [comment]
Is this supported yet?

**Comment by bitce** [comment]
HI @IchordeDionysos! There is no way to add a custom step from the GUI, you can only do so in the .yml
