### ISSUE TITLE
Duplicating workflow view when clicking on discard button, when page scrolled fully down

### ISSUE THREAD

**Issue by trapacska** [bitrise-io/bitrise-workflow-editor#146]

**Comment by viktorbenei** [comment]
Not just duplicating, but actually hiding all the Tabs, making it impossible to switch between Tabs!

E.g. scroll down in Workflow mode/tab, then (when you're at the bottom / scrolled down) switch to the Secrets tab -> the tabs are no longer available!

**Comment by erosdome** [comment]
fixed in v1.0.7, will be available on the website soon:

https://discuss.bitrise.io/t/workflow-editor-v1-0-7-released/1879
