### ISSUE TITLE
workflow ID: validate when WF is created!

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#148]
Right now the WF ID is only validated at "rename".

E.g. I can create a `print envs` workflow, with a space in it.

If I create it with "test" then try to rename it to "print envs" it will validate it and won't let me. But if you specify that during the creation of the workflow it'll let it.

**Comment by erosdome** [comment]
fixed in v1.0.7, will be available on the website soon:

https://discuss.bitrise.io/t/workflow-editor-v1-0-7-released/1879
