### ISSUE TITLE
bitrise.io only: if there are unsaved changes and you try to close the editor it won't let you, but no message is presented

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#149]
reproduction:

1. open any workflow on bitrise.io
1. modify anything
1. try to close the editor with the top right `X` or by clicking on the app's name in the breadcrumbs header

It won't let you leave (correct) but it won't present any message about why either (wrong).

Should present the same "you have unsaved changes" message as the one shown when you switch between Secrets/another tab.

**Comment by erosdome** [comment]
fixed in v1.0.7, will be available on the website soon:

https://discuss.bitrise.io/t/workflow-editor-v1-0-7-released/1879
