### ISSUE TITLE
Clicking the "Save" button closes the currently selected step

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#150]
Edit any step, then click the "Save" button - the step's details panel gets hidden.

Works if you use the "Cmd/Ctrl+S" hotkey, that does not hide/deselect the step

**Comment by erosdome** [comment]
fixed, will also be available on website soon:

https://discuss.bitrise.io/t/workflow-editor-v1-0-8-released/1919
