### ISSUE TITLE
Steps in Workflow - if step version is set to "always latest" - instead of printing only the current version of the also show that it's set to be "always latest"

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#152]
Right now it's really hard to see which steps are set to "always latest", you pretty much have to iterate over all the steps one by one.

![screenshot from 2017-06-01 12-19-25](https://cloud.githubusercontent.com/assets/430618/26675588/cb5ed4c6-46c4-11e7-88c3-a8e36b31cc68.png)

I think it's a good idea to present the "latest version of the step" (as it is right now) in the workflow step list even if the step is set to "always latest", but I'd also present the fact there that the step is set to be "always latest" and not that specific version which is shown there.

E.g. instead of just `1.3.1` I'd propose `always latest (1.3.1)` or `1.3.1 (always latest)` to be shown there (in workflow steps list, on the left side)

**Comment by erosdome** [comment]
added:

https://discuss.bitrise.io/t/workflow-editor-v1-0-9-released/2004

**Comment by erosdome** [comment]
Reopened due to suggestion from @viktorbenei: put `always latest` first, then the version

**Comment by erosdome** [comment]
Updated, will be available in next release.
