### ISSUE TITLE
Auto shutdown of server - doesn't work if there's any unsaved change

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#153]
Reproduction:

1. Open the editor
1. do any change which requires a save
1. don't save, just try to close the browser tab
1. a popup appears stating there are unsaved changes etc.
1. choose the "leave" option to leave/close the tab

The server should be closed, but it is not.

If there's no change / no "unsaved changes" popup the server is properly stopped, but not if there were any changes.

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
