### ISSUE TITLE
Click on "insert variable" - select any var in the popup - the step is deselected

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#154]
The env var is injected correctly, but you'll have to select the step & the input again after a variable insert, which is quite.. tedious

**Comment by viktorbenei** [comment]
Actually this also happens if you just click into the search/filter input in the Insert Variable popup, the step is deselected immediately

**Comment by erosdome** [comment]
updated, will also be available on website soon:

https://discuss.bitrise.io/t/workflow-editor-v1-0-8-released/1919
