### ISSUE TITLE
Default input value is not updated when changing step version

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#161]
Not sure if it is intended behavior or a bug.
For example in this step: [sonarqube-scanner](https://github.com/DroidsOnRoids/bitrise-step-sonarqube-scanner) `scanner_version` input variable default value has changed from `3.0.1.733` in version `1.0.0` to  `3.0.3.778` in `1.0.1`.
When step version is changed in selectbox then inputs (and perhaps rest of the form) is not reloaded to match new `step.yml`.

**Comment by viktorbenei** [comment]
Definitely a bug, thanks for reporting @koral--! 😊

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/workflow-editor-v1-0-9-released/2004
