### ISSUE TITLE
Make it possible to use get a UI for git:: style referenced steps on bitrise.io / in website mode

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#164]
Make it possible to use get a UI for git:: style referenced steps on bitrise.io. Right now this works in local (if you run the workflow editor locally with bitrise :workflow-editor) but not on bitrise.io; on bitrise.io you'll get a "placeholder" step on the UI where you can't set the inputs, only in bitrise.yml mode you can.

Technically this would mean that the workflow editor would know a couple of git hosting services (start with only GitHub for now, but make it so that it could be extended with other services in the future), and would be able to fetch the raw `YML` from there.

E.g.:

- `git::https://github.com/bitrise-steplib/steps-sign-apk.git@master`
- the `step.yml` is always in the root of the repo (https://github.com/bitrise-steplib/steps-sign-apk/blob/master/step.yml)
- and the raw URL of the yml, to get just the content: https://raw.githubusercontent.com/bitrise-steplib/steps-sign-apk/master/step.yml

**Comment by viktorbenei** [comment]
Related discussion: https://github.com/bitrise-io/bitrise-steplib/pull/1045

**Comment by erosdome** [comment]
Added for GitHub steps:

https://discuss.bitrise.io/t/workflow-editor-v1-0-10-released/2135
