### ISSUE TITLE
Do not start server / open the browser if there's no bitrise.yml in the current dir

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#166]
I tried to run the workflow editor in a dir where there was no `bitrise.yml`, and the editor did start and open in the browser, then simply printed **failed to load bitrise.yml/config** or something like that.

It's quite a bit confusing, I thought the issue was with the editor, but then I checked the terminal log:

```
bitrise :workflow-editor 
Starting API server at http://localhost:41889
Open workflow editor in browser ...
Created new window in existing browser session.
Failed to read bitrise.yml (bitrise.yml), error: No file found at path: bitrise.yml
````

And realized that I'm in the wrong dir.

## Proposal

Before starting the server & opening the browser window check whether there's a `bitrise.yml` file for the server at all and print a red error immediately, not starting the server at all.

**Comment by erosdome** [comment]
added:

https://discuss.bitrise.io/t/workflow-editor-v1-0-11-released/2219
