### ISSUE TITLE
Editor enters weird state when trying to download file using expired link

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#167]
When trying to download a file from Code Signing -> GENERIC FILE STORAGE section but link has expired, editor starts endless loading:
![image](https://user-images.githubusercontent.com/3340954/27361093-4ad89cc2-5625-11e7-8926-4c6cf9d035ee.png)
Even X button at the upper-right corner does not work.
Error message should be probably more user friendly and editor should not become unusable.

**Comment by viktorbenei** [comment]
Definitely, thanks for reporting @koral-- ! :)

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/workflow-editor-v1-0-10-released/2135
