### ISSUE TITLE
Newline characters changed to \n in bitrise.yml view

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#168]
I have a workflow with 2 script steps. One of them looks consistently in both Workflows and bitrise.yml tabs but 2nd one has newline characters replaced with `\n`.
![image](https://user-images.githubusercontent.com/3340954/27361519-2e977c88-5628-11e7-920b-fdb407465d2a.png)
![image](https://user-images.githubusercontent.com/3340954/27361537-4876454e-5628-11e7-8f7c-02bc8e26c48d.png)

Step have been added and edited using Workflows tab only. Content in that tab is the proper one.

**Comment by viktorbenei** [comment]
Hi @koral-- 

This is unfortunately a bit out of our control. Both representations are correct from a YML spec perspective, and so it depends on the serializer how it serializes that string content.

Added the `wontfix` label as we probably won't have enough time to dig into the go yaml lib (https://github.com/go-yaml/yaml), but of course contributions / PRs are always welcome!

**Comment by koral--** [comment]
Isn't it possible to just force particular style when content is modified in Workflow tab?
E.g. use multiline block beginning with `|-`.

**Comment by viktorbenei** [comment]
If you find an option in the docs (http://godoc.org/gopkg.in/yaml.v2 / https://github.com/go-yaml/yaml) please let us know! ;)

**Comment by koral--** [comment]
I guess PR should go there. Even if such will be made that lib does not seem to be contributor friendly: several dozens of issues and PRs opened months ago and this: https://github.com/go-yaml/yaml/issues/261

**Comment by viktorbenei** [comment]
It's quite a stable lib, we never had any issue with it, that might explain the lack of activity there, but of course there's always room for improvement.. To be honest this is like the de factor Go standard YAML lib, switching to any other would be quite a risk

**Comment by koral--** [comment]
I've managed to determine the scenario in which content is "squashed".
It happens when there is a chain of whitespaces at the end of an input beginning with space character. For example: one space, space + newline etc.
It does not happen when there are newlines only.

I guess that if there are only spaces a the end, text may be intentionally enclosed with double quotes to preserve it and this is only valid solution.

However, if there are spaces followed by newlines both block and quoted text can be used.
Right?

**Comment by viktorbenei** [comment]
> I guess that if there are only spaces a the end, text may be intentionally enclosed with double quotes to preserve it and this is only valid solution.

That would make sense. Technically it'd be possible to keep the line ending spaces in the non double quoted form I believe, but the double quoted form is definitely more reliable / less error prone as a serialized form.

> However, if there are spaces followed by newlines both block and quoted text can be used. Right?

I think technically that should be possible.

**Comment by viktorbenei** [comment]
> So, to sum up, it seems that the only feasible action for this is to fill an issue on https://github.com/go-yaml/yaml

Indeed. I believe we tried to find another YAML lib for Go initially when we saw this same issue, but did not find any suitable alternative.

**Comment by doomsayer13** [comment]
@koral-- are you still facing the issue?

**Comment by koral--** [comment]
Yep, just checked and it is still present. Moreover, it seems that now text is a single, quoted line always if there is any whitespace at the end including single newline.

**Comment by jbweimar** [comment]
Still this still an issue and super-annoying. Unfortunately, Bitrise seems to have many of these little bugs (also UI/UX issues) that might cause our company to choose another option.

**Comment by paramaggarwal** [comment]
**Workaround**: Just avoid having a space at the end of any line.
