### ISSUE TITLE
Invalid markdown rendering in texts enclosed with quotes

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#169]
For example this text: https://github.com/peartherapeutics/bitrise-aws-device-farm-file-deploy/blob/master/step.yml#L64
looks like that in editor:
![image](https://user-images.githubusercontent.com/3340954/27400289-ee5d9e02-56bf-11e7-8fb5-7bfa3c4167a9.png)

but it should like that:
ex. `APPIUM_PYTHON_TEST_PACKAGE`. See [Upload.type documentation](http://docs.aws.amazon.com/devicefarm/latest/APIReference/API_Upload.html#devicefarm-Type-Upload-type).

On the other hand this one using multiline description (`|-` block): https://github.com/DroidsOnRoids/bitrise-step-sonarqube-scanner/blob/master/step.yml#L46
is displayed properly.

**Comment by viktorbenei** [comment]
It's not a workflow editor / rendering issue :) 

The step you're referring to was updated recently, but the new version was just shared into the StepLib.

E.g. check the same line at v0.0.3 of the step: https://github.com/peartherapeutics/bitrise-aws-device-farm-file-deploy/blob/0.0.3/step.yml#L64

I'll close this here (for tracking purposes), but feel free to comment, we're tracking closed issues/tickets too ;)

**Comment by viktorbenei** [comment]
The issue in your example above is that the `something_with_underscore` was not wrapped in back-ticks previously, and `_` (underscore) in Markdown means italic. The latest version of the step now has it wrapped in backticks and should render properly (was just accepted a few minutes ago)

**Comment by koral--** [comment]
Wow, issue resolved before reporting 👍

**Comment by viktorbenei** [comment]
Yeah, you created the issue just a few mins before the PR was accepted (https://github.com/bitrise-io/bitrise-steplib/pull/1074) :D
