### ISSUE TITLE
Steps version information inconsistent across different users

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#171]
For example, the newest version of Git clone step which I can see (logged in using GitHub) at the time of writing is 3.4.4 while another user sees 3.5.0.
In workflows with version already set to 3.5.0 I see default step icon.
Reproducible on all apps we can see.
![image](https://user-images.githubusercontent.com/3340954/27543767-6991b508-5a8b-11e7-83a5-ef9c1d8c2292.png)
![image](https://user-images.githubusercontent.com/3340954/27543810-9a5b24ee-5a8b-11e7-9387-96110aee85f5.png)

**Comment by viktorbenei** [comment]
This is due to caching in your web browser. Please reload the editor/page a couple of times until the browser reloads the StepLib.

**Comment by koral--** [comment]
I don't know how that cache works internally so, correct me if I'm wrong. Couldn't cache be automatically invalidated in such cases?
I mean:

1. Version newer than newest available (taking cache into account) is found in bitrise.yml.
2. Editor checks (w/o cache) if it is valid.
3. If so, cache is invalidated or just this one entry is refreshed.

It seems that p. 1. is already detected programmatically, because there is a corresponding message in JS console: `main.js:60631 Step with version not found in library: 3.5.0`

**Comment by viktorbenei** [comment]
The StepLib is distributed as a JSON file on bitrise.io, so if your browser does not download it (because it's already in the browser's cache) you'll get the cached steplib JSON.

Feel free to open a ticket in [stepman](https://github.com/bitrise-io/stepman) or in the StepLib; unfortunately the current steplib JSON distribution is simply updating it on Amazon S3, so it's up to S3 and your browser to check when the JSON have to be updated, the workflow editor itself can't do anything about it.

**Comment by koral--** [comment]
OK, I understand that is out of your control and I'll give up here in that matter.
However, one more question: How to explain an orange badge on the 1st screenshot?
The version is already the newest (in reality) or even newer (according to the cache) than the newest available. So badge should not be shown.

**Comment by viktorbenei** [comment]
> However, one more question: How to explain an orange badge on the 1st screenshot?

From the StepLib's perspective the latest version of the step is the version included in the steplib. Until there's info about a given version in the StepLib it's not considered latest even if the version number of it is (supposedly) higher. This will be resolved once the caching improvement is implemented in `stepman` of course.

**Comment by koral--** [comment]
OK, everything is clear now.

**Comment by viktorbenei** [comment]
If you'd have any questions or suggestions we're always happy to help / discuss! ;)
