### ISSUE TITLE
Workflow overwritten without notice when name changed in bitrise.yml

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#172]
Steps to reproduce:
1. Have at least 2 distinct workflows
2. Rename one of them like the 2nd one (using bitrise.yml tab)
3. Save workflow

Actual result:
Step is overwritten.

Expected result:
Either there should be some kind of prompt with confirmation that workflow will be overwritten or there should be an error thrown when saving.

**Comment by viktorbenei** [comment]
Thanks for the report @koral-- :)

@erosdome added to internal tracker

**Comment by erosdome** [comment]
@viktorbenei it seems that saving in YML mode accepts, and even stores duplicate keys (saved with duplicate keys, reloaded, still there), but in JSON mode (which we use on the other tabs) it is discarded. Don't know what can be done to raise error in this case, @godrei says the parser simply strips the duplicate key, but cannot detect that it was a duplicate.

**Comment by viktorbenei** [comment]
@erosdome if you save in YML mode then the YML is not processed just validated, but saved as-it-is, the way you send it (AFAIK)

JSON mode parses the YML to convert it to JSON

What can be done: don't allow the workflow to be named the same as another workflow, on the UI. In bitrise.yml mode unfortunately there's nothing you can do right now, but on the UI you definitely can ;)
(The CLI/YML mode specific issue is tracked separate at https://github.com/bitrise-io/bitrise/issues/517 )

**Comment by koral--** [comment]
> What can be done: don't allow the workflow to be named the same as another workflow, on the UI. In bitrise.yml mode unfortunately there's nothing you can do right now, but on the UI you definitely can 

Not sure if this the new case intentionally added to this issue or misunderstanding but 1st comment is about bitrise.yml mode only.

In UI mode (assuming it is the same thing as Workflows tab), normally, it is not possible to confirm duplicated name because ✓ button is inactive.

**Comment by viktorbenei** [comment]
Ahh, ok, I was a bit out of loop (too much multi tasking..)

Will close this issue here, tracking at: https://github.com/bitrise-io/bitrise/issues/517
