### ISSUE TITLE
Inputs without category - section should be opened by default

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#174]

**Comment by viktorbenei** [comment]
Pretty hard to tell that the step has any inputs in this case:

![screenshot from 2017-07-03 11-04-48](https://user-images.githubusercontent.com/430618/27785954-8bc4af6e-5fdf-11e7-8f35-82b4ec9d3e27.png)

That section should be expanded by default like this:

![screenshot from 2017-07-03 11-05-00](https://user-images.githubusercontent.com/430618/27785969-9a129a7c-5fdf-11e7-9e1b-15e72c513488.png)

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/workflow-editor-v1-0-11-released/2219
