### ISSUE TITLE
Insert variable button in fields with is_expand: false

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#179]
`Insert variable` button seems to appear for all the text input fields. However, when an input is marked `is_expand: false` variable value won't be actually inserted. Is it intended?

![image](https://user-images.githubusercontent.com/3340954/27876468-87b55656-61b7-11e7-85e6-5c0c1076d626.png)

**Comment by viktorbenei** [comment]
That's the correct behaviour. E.g. in the Script step (the one you shot the screenshot about) you still can use those Env Vars, it's just that the CLI itself won't replace it **before** passing to the step. But the step is free to do anything with that input. More info: http://devcenter.bitrise.io/getting-started/manage-your-bitrise-workflow/#environment-variable-replace-mode
