### ISSUE TITLE
Entering weird state after launching worklflow editor from build page 

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#190]
Steps to reproduce:
- Click "click here" in hint frame:
![image](https://user-images.githubusercontent.com/3340954/29727792-96caca90-89d5-11e7-929c-c47e76369508.png)
after that window title is still "build #<build number>", but tab works
- go back in browser
tab becomes empty
![image](https://user-images.githubusercontent.com/3340954/29727924-2c27d934-89d6-11e7-9051-afc9772cb94c.png)

**Comment by viktorbenei** [comment]
Thanks for reporting @koral-- !

@erosdome 👀

**Comment by koral--** [comment]
Ad step 2. it seems that workflow editor just breaks when back in browser is used. It becomes empty and covers actual page.

Another example:

1. open app builds page in new tab (history is empty initially), I used this app: https://www.bitrise.io/app/589b4f36b94c12c1#/builds
2. open workflow editor tab
3. go back in browser - nothing visible happens
4. go back again - workflow tab becomes empty, like on 2nd screenshot
5. go back again - content does not change, but URL switches to initial one

After closing workflow editor by X button in upper right corner, actual page content is revealed. This the same workaround as mentioned in https://github.com/bitrise-io/bitrise-workflow-editor/issues/105#issuecomment-301229373.

**Comment by erosdome** [comment]
Overriding the behaviour of the back button is rather limited, although managed to work out a solution: it now closes the workflow editor.

https://discuss.bitrise.io/t/workflow-editor-v1-0-15-released/2863
