### ISSUE TITLE
UI for the new step timeout parameter (introduced in CLI 1.9.0) [FEATURE-REQUEST]

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#192]
Introduced in https://github.com/bitrise-io/bitrise/releases/tag/1.9.0

The new `timeout:` step param should be exposed on the UI somehow

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
