### ISSUE TITLE
Errors when saving secret environment variable

### ISSUE THREAD

**Issue by everlof** [bitrise-io/bitrise-workflow-editor#196]
Workflow editor: v1.0.14

I try to save the key like this:

<img width="681" alt="screen shot 2017-09-27 at 16 42 00" src="https://user-images.githubusercontent.com/1321434/30920022-3f28dede-a3a3-11e7-8cbc-0d78ff43bc4b.png">

I'll get this error inte browser:

<img width="627" alt="screen shot 2017-09-27 at 16 41 46" src="https://user-images.githubusercontent.com/1321434/30919866-e4c9e56e-a3a2-11e7-8f50-9bbed6ba2a07.png">

And this error in the console:

```
Invalid secrets: Validation failed: Secret validation error: Failed to get inventory from base 64 data, err: Failed to normalize bitrise inventory, error: not supported key found in options: meta
 => POST: /api/secrets - 26.446885ms (application/json;charset=UTF-8)
```

**Comment by godrei** [comment]
Hi, thanks for the report, we will fix this asap!

**Comment by erosdome** [comment]
Hi. The new workflow editor requires a newer version of Bitrise CLI. Please update it, that should fix the issue. In our next release we will include the newer version as a requirement, so further upgrades of the workflow editor will not be available until the CLI is on the correct version.

**Comment by everlof** [comment]
Thank @erosdome! I can verify that the new version does fix the issue for me 👍

**Comment by erosdome** [comment]
Version requirement update in v1.0.16:

https://discuss.bitrise.io/t/workflow-editor-v1-0-16-released/2905
