### ISSUE TITLE
Keyboard shortcuts with a "list/help" overview popup

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#20]
Ala https://discuss.bitrise.io/ - hit `?` to get a full list of available keyboard shortcuts

Essentials:

- save
- switch workflow (similar to switch org at https://www.bitrise.io/me/profile#/overview)
- switch to view mode: workflows, secrets, env vars, triggers, ...
- delete step
- add new step
- ...

**Comment by doomsayer13** [comment]
Clickup card created and also I added this feature request to our discuss feature request channel:
https://discuss.bitrise.io/t/keyboard-shortcuts-with-a-list-help-overview-popup-in-workflow-editor/6219

**Comment by viktorbenei** [comment]
Thanks @doomsayer13 ! ;)

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
