### ISSUE TITLE
Comments in `bitrise.yml` lost when saving/loading

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#206]
Steps to reproduce:

1. write a comment in `bitrise.yml` tab
2. save yml
3. refresh page or download saved config

Comments are lost.

**Comment by viktorbenei** [comment]
Unfortunately as soon as you parse a yml with any parser comments are lost (because by definition comments are ignored by the parser).

You can find a related discussion and some tips and notes here: https://discuss.bitrise.io/t/saving-comments-in-bitrise-yml/423/2

**Comment by viktorbenei** [comment]
I'll close this here, but if you have any questions @koral-- feel free to comment on discuss! :)
