### ISSUE TITLE
Invalid verified badge and repo URL for git:: steps

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#207]
Steps to reproduce:
1. Add step having git:: source, I've used this: https://github.com/DroidsOnRoids/steps-hockeyapp-android-deploy/ branch `split-apks`

Github icon is linked to the parent repo, not the fork from specification. Additionally verified badge is shown.
![image](https://user-images.githubusercontent.com/3340954/32063089-9e985e96-ba76-11e7-9f1d-ea842dada755.png)

I guess that workflow editor checks for those information using `STEP_ID_IN_STEPLIB` only and ignores git:: URL.

**Comment by doomsayer13** [comment]
Hi @koral-- 
Thanks for reporting

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/workflow-editor-v1-0-20-released/3293
