### ISSUE TITLE
Online workflow editor could not edit steps without configuration

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#212]
To reproduce add a step like that:
`    - cache-pull@2.0.0: `
`null` and `~` instead of nothing also works.

Step is saved successfully in bitrise.yml mode, but cannot be edited in visual mode. All the inputs are undefined, even if they have default values. Changing anything does not activate save button.
![image](https://user-images.githubusercontent.com/3340954/32356343-c9e527aa-c034-11e7-817c-cbedc4c528d2.png)

It is not reproducible offline in v1.0.18.

**Comment by viktorbenei** [comment]
Reproduced on bitrise.io, thanks for the report @koral-- !

@erosdome pls schedule a fix

**Comment by erosdome** [comment]
fixed in 1.0.20, will be updated on website when its workflow version is updated:

https://discuss.bitrise.io/t/workflow-editor-v1-0-20-released/3293
