### ISSUE TITLE
Remember the workflow when switching between Env Vars & Workflows

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#214]
E.g. if I want to look up an app env var or workflow env var set on Env Vars, it'd be awesome if when switching back to Workflows the same workflow would be selected as the one I switched from to Env Vars

**Comment by erosdome** [comment]
feature added, also the same step is selected as well:

https://discuss.bitrise.io/t/workflow-editor-v1-0-20-released/3293
