### ISSUE TITLE
hotkey / shortcut for switching between workflows

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#215]
it'd make it so much faster to work with workflows if I could switch between workflows via keyboard shortcut ;)

**Comment by bloodrabbit** [comment]
How about cmd/ctrl+K ?

**Comment by viktorbenei** [comment]
Cmd + K is OK with me, or even just `/`

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
