### ISSUE TITLE
Workflow list: include a filter / search input field to filter the workflows

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#226]
When you have lots of workflows it would be incredibly helpful if we could search between those, e.g. similar to how the "branch" search/filter works on bitrise.io on the build list page.

**Comment by viktorbenei** [comment]
Semi-related to https://github.com/bitrise-io/bitrise-workflow-editor/issues/215

A hotkey for showing the workflow list & moving the focus right into the filter / search input field (e.g. how it works on Heroku with the `/` key) would be super awesome! ;)

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
