### ISSUE TITLE
On the triggers page discard button misbehaves

### ISSUE THREAD

**Issue by ghaabor** [bitrise-io/bitrise-workflow-editor#232]
When you add a new trigger and you change your mind halfway (you've never clicked "Done" for the trigger so it's not actually added) and you click on "Discard" it clears the trigger list, but Discard stays active and if you click it again your original triggers are now back.

Steps to reproduce:

1. Open Triggers tab
2. Click "Add trigger" on a page where you already have a trigger
3. Do NOT click on Done or Cancel
4. Click Discard in top right corner
5. ???
6. Click Discard again

**Comment by doomsayer13** [comment]
This PR will fix the issue #233

**Comment by erosdome** [comment]
The fix for this issue has been released: https://discuss.bitrise.io/t/workflow-editor-v1-1-3-released/3636
