### ISSUE TITLE
Show warning when adding a "before run" workflow to another workflow and they have different stacks

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#267]
Because in this case, the "before run" workflow's stack will be used throughout the whole build. @viktorbenei wdyt?

UPDATE: Indeed, the original workflow's stack will be used. So the warning should be about the "before run" workflow not having its expected stack used.

**Comment by viktorbenei** [comment]
Warning is OK, but that's not how it supposed to work @erosdome ;)

The workflow you trigger specifies the stack. No before or after workflow should change that. If you trigger workflow A then only workflow A should be considered. And I think that is actually the case right now ;)

**Comment by erosdome** [comment]
True, updated the description :)

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
