### ISSUE TITLE
Android Keystore Metadata not being saved

### ISSUE THREAD

**Issue by nickarora** [bitrise-io/bitrise-workflow-editor#269]
Steps to reproduce:

1. Upload a keystore
2. Specify the metadata / passwords
3. Click Save Metadata
4. then reload the page
Metadata are gone :/

same as: https://github.com/bitrise-io/bitrise-workflow-editor/issues/113
which was previously closed

**Comment by viktorbenei** [comment]
Thanks for reporting @nickarora !

Can you please try it from an Incognito window / from another browser too?

**Comment by erosdome** [comment]
This received a UI update which I believe fixes the issue:

https://discuss.bitrise.io/t/workflow-editor-v1-1-16-released/4850
