### ISSUE TITLE
Workflow editor loading time

### ISSUE THREAD

**Issue by Kaniz92** [bitrise-io/bitrise-workflow-editor#271]
Workflow editor seems like forever to get load. This occurred to me several times after editing bitrise.yml

![bug](https://user-images.githubusercontent.com/31236289/37444881-31c6967a-283a-11e8-874d-16446a008c3a.PNG)

**Comment by viktorbenei** [comment]
Hi @Kaniz92 ,

Did you try it in a different browser / in an incognito window or tab?

**Comment by Kaniz92** [comment]
Didn't get a chance to try in different browsers. 
Somehow I figured that I left the 'trigger_map:' attribute name without the content which caused the error.
Thanks.

**Comment by viktorbenei** [comment]
Got it - thanks for reporting @Kaniz92 ! We'll discuss how we could improve the error here :)
