### ISSUE TITLE
Please print the full URL of where the editor is running

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#283]
Right now only the base URL is printed:

```
$ bitrise :workflow-editor

Searching for bitrise.yml at: /private/tmp/qq/bitrise.yml
Starting API server at http://localhost:52223
Open workflow editor in browser ...
```

But if I open `http://localhost:52223` I get `404 page not found`.

The proper full URL in this case was `http://localhost:52223/1.1.14`, that works.

---

Use case: any case when the editor can't be opened in the browser directly, e.g. because you run it in a docker container or similar. In that case you can of course still open the URL manually, but the plugin itself can't open the browser.

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
