### ISSUE TITLE
Allow specification of config to edit

### ISSUE THREAD

**Issue by fadookie** [bitrise-io/bitrise-workflow-editor#284]
It would be nice if you could specify the path/name of the `bitrise.yml` you are editing in the same way that `bitrise run` can be given a `--config` flag. I'm not sure the proper way to handle `.bitrise.secrets.yml` in this setup but it should match how `bitrise run` handles it.

**Comment by viktorbenei** [comment]
Great idea, thanks for the feature request @fadookie ! :)

**Comment by luispadron** [comment]
Would love this as well, any pointers on how to implement this? 🙏🏼

**Comment by Roland-Bak** [comment]
Hello @luispadron 👋

There is no feature for this out as far as I know, but I'll bring this to our Product Team for consideration! 🙂
