### ISSUE TITLE
YML mode lagging in mobile Safari

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#297]
User who reported: https://discuss.bitrise.io/t/website-is-unusable-on-safari/5597/2

**Comment by fwigorcferreira** [comment]
This bug was seem on:

```
MacBook Pro (15-inch, 2017)
macOS High Sierra 10.13
Safari 11.1.1
```

and

```
MacBook Pro (15-inch, 2015)
macOS High Sierra 10.12
Safari 11.1.1
```

**Comment by fwigorcferreira** [comment]
@erosdome I used the latest version on local machine. And it is not solved!!! When accessing the YML editor from Safari, it has a horrible delay when doing anything on it. I'll retry on later, when a new version is available in the website. But, I believe that this is NOT FIXED.
