### ISSUE TITLE
Unable to access Env Var panel on mobile Safari

### ISSUE THREAD

**Issue by fwigorcferreira** [bitrise-io/bitrise-workflow-editor#312]
This is the same as the issue #298 that was NOT fixed.

As tested in the v1.1.24, it is impossible to access the env var panel when using Safari on iPhone.

Recording of the issue:
https://www.dropbox.com/s/9uooqi6ipx2pu6h/env_var_problem.MP4?dl=0

This bug is happening on:

```
iPhone X
iOS 11.4

iPhone 6
iOS 11.0.1

iPhone 6s
iOS 10.3
```

**Comment by fwigorcferreira** [comment]
Again: The video is cropped to a few minutes. But I stayed looking to this white screen for more than 5 minutes.

**Comment by sylank** [comment]
Hi @fwigorcferreira 

We implemented a lot of new features and took many refactors since last year. Could you check this issue again? If it not presenting I will close the issue.

Thanks
