### ISSUE TITLE
Mobile view - when scrolling > the parent view scrolls and not the workflow editor view

### ISSUE THREAD

**Issue by fwigorcferreira** [bitrise-io/bitrise-workflow-editor#313]
This is related to the issue #141 that was not solved.

When scrolling in the workflow view, the background scrolls, but the front view doesn't

https://www.dropbox.com/s/q7w3woe6rdq1eor/scroll_problem.MP4?dl=0

This bug was seem on:

```
iPhone X
iOS 11.4

iPhone 6
iOS 11.0.1

iPhone 6s
iOS 10.3
```

**Comment by erosdome** [comment]
Hi, we’ve just released a fix for the website (Workflow editor version 1.1.29), which focuses on the scrolling issue. It should be fixed now, could you check if it is working for you too?

**Comment by fwigorcferreira** [comment]
@erosdome The latest version has the scroll fixed. But, it broke the load of the env vars. on v1.1.28 it loaded after nearly 1 minute. Now, it is not loading at all.

**Comment by erosdome** [comment]
Also, it seems scrolling is broken for the other tabs. Reverting this fix, so it looks like the final one will take more time unfortunately. Sorry for the inconvenience.

**Comment by sylank** [comment]
Hi @fwigorcferreira 

Is this issue still present? Could you test it again? I will close this issue, but if you find a new issue please create a new one and we will investigate the problem again. 
Thank you for your contribution 😸
