### ISSUE TITLE
YML mode lagging in Safari (Desktop)

### ISSUE THREAD

**Issue by fwigorcferreira** [bitrise-io/bitrise-workflow-editor#314]
This is related to the issue #297 that was not solved.

The YML editor is UNUSABLE on Safari.

Given the sensibility of the information recorded, I won't send the link here. But I've sent in the site support chat.

This bug was seem on:

```
MacBook Pro (15-inch, 2017)
macOS High Sierra 10.13
Safari 11.1.1
```

and

```
MacBook Pro (15-inch, 2015)
macOS High Sierra 10.12
Safari 11.1.1
```

**Comment by dbreuer** [comment]
Hi @fwigorcferreira 
We found a solution for the **bug 3**, so the **YML Editor** currently using **Ace Editor** engine and we going to replace this with **Monaco Editor** (VS Code). We will let you know as soon as it is released.

Thank you for your patience.

**Comment by dbreuer** [comment]
Fixed by Switch from ACE editor to Monaco editor #315, keep it open until confirmation

**Comment by bitrise-adam** [comment]
Hi @fwigorcferreira 

Can you confirm that this issue is now resolved for you?

Thanks

**Comment by fwigorcferreira** [comment]
@dbreuer @bitrise-adam Hello, I tested the new editor using the v1.1.28, and it works fine on Safari 11.1.2, macOS 10.13.6 on a MacBook Pro (15-inch, 2017). Thanks, very much.

**Comment by bitrise-adam** [comment]
Thanks for testing, glad to hear it's working now @fwigorcferreira I'll close this issue
