### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mackoj** [bitrise-io/bitrise-workflow-editor#334]
Hi I have this error when I try to install the workflow editor.
Can you help me ?

```
$>bitrise plugin install --source https://github.com/bitrise-io/bitrise-workflow-editor.git --version 1.1.33
Installing plugin
Plugin install failed, error: plugin validation failed, error: failed to get current version map, error: exit status 1
```

**Comment by mackoj** [comment]
After further investigation I didn't have `go` installed on my computer after installing `go` I tried again `bitrise plugin install --source https://github.com/bitrise-io/bitrise-workflow-editor.git --version 1.1.33` 
and it worked please consider update your documentation.

**Comment by bitce** [comment]
Hey @mackoj sorry for the inconvenience and thanks for the feedback! All in all I'm glad you've found this out quickly.
