### ISSUE TITLE
mark deprecated steps!

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#35]
In the step list, similar to steps which have updates. Or maybe even more.

+ present the "deprecation note" message somewhere for the step, those usually include a recommended migration guide, e.g. switch to step X instead.

**Comment by doomsayer13** [comment]
Also do not list them in the step list.

**Comment by erosdome** [comment]
deprecation badge added:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-10-released/1696
