### ISSUE TITLE
Cannot set a fixed port for running workflow-editor server

### ISSUE THREAD

**Issue by miguelfreitas93** [bitrise-io/bitrise-workflow-editor#360]
Hi,

I'm running bitrise CLI over a docker container, since the OS of my host machine is Windows.

Container does not has access to the browser, so I want to be able to browse it on my host machine.

To do that, I need to map/expose the port of the container to the port of host I wanna use.

Since when you start the workflow-editor server the port used is random, I'm not able to browse the editor on my host machine.

I tried to map a range of ports like 30000-40000 but as part this is very inefficient, docker has also some issues to map such a big range of ports.

So my suggestion is to add the ability to configure the port for the workflow-editor server.

Thanks !

**Comment by fehersanyi-bitrise** [comment]
Hello @miguelfreitas93 !

If you set up the env var $PORT to the build, it will use it by default, if not then it will be random.
So you can define the workflow editors port to use and the one you want to use as well.

**Comment by miguelfreitas93** [comment]
@fehersanyi-bitrise thanks
