### ISSUE TITLE
Variable not showing up in some case

### ISSUE THREAD

**Issue by mackoj** [bitrise-io/bitrise-workflow-editor#372]
Hi,

When I add a variable in a workflow and I try to use this variable in a sub workflow it didn't show up in the variable windows.

Workflow1
|- SubWorkflow
|---Step (try to access a variable define in en env menu but is not showing up)

## Env Menu

![Capture d’écran 2019-05-15 à 15 18 17](https://user-images.githubusercontent.com/661647/57790477-1cb65d00-773b-11e9-8cc0-3adfcb0f8940.png)

## Workflow Editor

![Capture d’écran 2019-05-15 à 15 18 36](https://user-images.githubusercontent.com/661647/57790517-30fa5a00-773b-11e9-9aed-d10f138f3dce.png)

## Variable Window

![Capture d’écran 2019-05-15 à 15 19 11](https://user-images.githubusercontent.com/661647/57790546-4079a300-773b-11e9-9e33-ca09b8b315ee.png)

**Comment by bitce** [comment]
Hi @mackoj!

Maybe I'm misunderstanding, to me this seems like expected behaviour, since you're adding these env_vars as a workflow specific env_var to the 'Deploy_Dev' workflow. This means that only that one can access it, regardless of workflows running before/after it chained together.

**Comment by mackoj** [comment]
It make sense sorry for the ticket Îm closing it.

**Comment by bitce** [comment]
No worries! Thanks for all the help :)
