### ISSUE TITLE
Generic File Storage Flicker

### ISSUE THREAD

**Issue by rhoberman** [bitrise-io/bitrise-workflow-editor#373]
The Code Signing tab flickers when one or more generic files have been created but not yet uploaded. This is visually disturbing and difficult to resolve through the UI.

Steps to reproduce:

1. Create a generic file:

`curl -X POST “https://api.bitrise.io/v0.1/apps/MYSLUGXXX/generic-project-files” -H “accept: application/json” -H “Authorization: MYACCESSTOKENXXX” -H “Content-Type: application/json” -d “{ “upload_file_name”: “Test-File”, “upload_file_size”: 4865, “user_env_key”: “TestFile9875”}”

2. (Don't upload the file)
3. Open the Workflow editor for your project
4. Navigate to the Code Signing tab
5. Scroll down to the Generic File Storage section
6. Observe that this section continually disappears and reappears (see attached video)

This is visually painful and it is very difficult to delete the entry using the drop down menu as the page typically rerenders before you can open the menu and hit "delete".

This seems to be caused by the UI is refreshing while waiting for the file to be uploaded so that it can update when the file arrives. 

[generic_file_storage_flicker.mov.zip](https://github.com/bitrise-io/bitrise-workflow-editor/files/3191304/generic_file_storage_flicker.mov.zip)

**Comment by fehersanyi-bitrise** [comment]
Hello @rhoberman 

This exactly is the issue, the frontend refreshes and tries to get the data from the backend, but the file is not there so it tries to get it again.

I'm sorry if it is disturbing, you should just upload the file properly.

**Comment by rhoberman** [comment]
Hi @fehersanyi-bitrise 

Is there a way to avoid updating the component until the upload is completed? Perhaps the handling of the repeated checking could be moved to a component that is invisible (or a loading icon)? Then the component representing the generic file can be updated a single time once it is complete?

I realise this may not affect many users. I encountered this while dealing with an API problem that prevented me from completing uploads (see https://discuss.bitrise.io/t/solved-no-longer-able-to-post-generic-project-files-key-not-unique/9027).

**Comment by bitce** [comment]
Hi @rhoberman!

That's a fair point! We actually have an ongoing task about investigating this issue, it just happens rarely and is hard to, thanks for your report!

**Comment by sylank** [comment]
Hi @rhoberman 

We have just released the Workflow Editor 1.1.56. This release will solve this issue.

Please, test it again and if everything makes sense to you, close the issue :).

Please find the related topics:
https://github.com/bitrise-io/bitrise-workflow-editor/pull/375
https://github.com/bitrise-io/bitrise-workflow-editor/releases/tag/1.1.56
https://discuss.bitrise.io/t/workflow-editor-v1-1-56-released/9201
