### ISSUE TITLE
When changing a secret's PR exposure I have to change the text field to save

### ISSUE THREAD

**Issue by samsonjs** [bitrise-io/bitrise-workflow-editor#382]
I wanted to flip the PR switch on a secret env var but the save button was disabled until I made a change in the text field. It was a bit confusing.

**Comment by bitce** [comment]
Hi @samsonjs, thanks for reporting this, to clarify, you don't need to press "Edit" to flip the toggle button at all.

**Comment by samsonjs** [comment]
🤦🏻‍♂️ Thanks for the reply!
