### ISSUE TITLE
Step version number is not up to date on workflow editor

### ISSUE THREAD

**Issue by TeamiOSolocal** [bitrise-io/bitrise-workflow-editor#385]
Hello

When I run my workflow, it tells me that I have to update my step to last version (see first screenshot below) ... but when I go to bitrise workflow editor, last asked version is not visible and actual selection seems to be the last one (see second screenshot below)...

Best regards

Jérémie

**Screenshot 1**
![Capture d’écran 2019-09-04 à 16 19 04](https://user-images.githubusercontent.com/50584108/64263360-cfe7d380-cf2f-11e9-89ff-aafaa3ab99c0.png)

**Screenshot 2**
![Capture d’écran 2019-09-04 à 16 18 50](https://user-images.githubusercontent.com/50584108/64263342-c8c0c580-cf2f-11e9-9f14-fd1c256e17f6.png)

**Comment by bitce** [comment]
Hi @TeamiOSolocal! Can you try force cache update the website? The version is released and available but browsers sessions often cache a previous state of the website and because of this you might not see it right away.

**Comment by mackoj** [comment]
How can we force update it ?

**Comment by bitce** [comment]
@mackoj Depends on browser type and OS version, here's a [related example article](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.XXG93pMzY_U).

**Comment by mackoj** [comment]
I know how to reload my browser 😁
The issue is that workflow-editor don't always show updates.

**Comment by bitce** [comment]
Well, it's definitely more technical than a regular reload 😅 but yes, I completely understand the issue, we've noticed it multiple times for the above-mentioned reasons and the steps I'm referring to here have been proved to make them appear.
