### ISSUE TITLE
cannot create secret

### ISSUE THREAD

**Issue by frakc** [bitrise-io/bitrise-workflow-editor#402]
When i trying to add secret I receive error as on screenshot
![Снимок экрана 2019-11-27 в 17 14 08](https://user-images.githubusercontent.com/1126230/69735624-a955c500-1139-11ea-91e2-864fefae1b37.png)

**Comment by tamasbazs** [comment]
Hi @frakc ,

We are really sorry for the inconvenience caused! Our Website team is currently working on deploying a fix for this issue. We'll update you as soon as the fix is our!
