### ISSUE TITLE
validate environment variable KEYs

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#41]
based on http://stackoverflow.com/a/2821183/974381

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.

**Comment by viktorbenei** [comment]
We didn't have any issues with lowercase letters, but it's important that you can't use `-` or space in the key, and __the key can't start with a digit__ (we had an issue with this).

**Comment by erosdome** [comment]
A fix has been implemented and should be out with the next release

**Comment by viktorbenei** [comment]
😱 🚀 🎉

**Comment by erosdome** [comment]
Fixed with v0.9.3. release. More information:
https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-3-released/650
