### ISSUE TITLE
"Failed to load workflows."

### ISSUE THREAD

**Issue by everlof** [bitrise-io/bitrise-workflow-editor#42]
Bitrise CLI version: 1.5.3
Plugin version: 0.9.2

In the root of my repo I write:
`bitrise :workflow-editor`

And I get the following output:
```
Starting API server at http://localhost:3645
Open workflow editor in browser ...
 => GET: /api/bitrise-yml.json - 20.332667ms ()
empty output data
 => POST: /api/spec - 43.941114ms (application/json;charset=UTF-8)
```

My `bitrise.yml` is in the root of the repo as well.

This is what I see in my browser:

![screen shot 2017-02-06 at 08 06 20](https://cloud.githubusercontent.com/assets/1321434/22637624/35c3fcf6-ec43-11e6-859c-d7824cce1417.png)

**Comment by viktorbenei** [comment]
Thanks for reporting @everlof !

@erosdome pls have a look! ;)

**Comment by erosdome** [comment]
@godrei ?

**Comment by everlof** [comment]
I can add some more info:

![screen shot 2017-02-06 at 12 39 49](https://cloud.githubusercontent.com/assets/1321434/22645849/6fc6ab08-ec69-11e6-8c6f-9ced1e5f7256.png)

**Comment by godrei** [comment]
Hi @everlof ,

could you please share your bitrise.yml with us?

**Comment by everlof** [comment]
Can I perhaps share it to you in a private manner?

**Comment by godrei** [comment]
Sure, could you please write a message on bitrise on-site chat? i will assign the conversation to me.

**Comment by everlof** [comment]
I've upgraded to 0.9.3 and can't reproduce it anymore!

**Comment by viktorbenei** [comment]
Awesome, thanks for reporting @everlof ! 😉
