### ISSUE TITLE
Unable to re-name a workflow step

### ISSUE THREAD

**Issue by paul-anaplan** [bitrise-io/bitrise-workflow-editor#449]
**Steps to reproduce**
1) Open an existing workflow
2) Add a new step to the workflow (for example, a `Script` step)
3) Click on the step name (which is a `button` element with the class `rename`)
<img width="852" alt="Screenshot 2020-02-26 at 11 30 40" src="https://user-images.githubusercontent.com/59557119/75341227-e55d0b00-588b-11ea-86aa-1e52e3c91517.png">

_Actual outcome_
The button remains in place

_Expected outcome_
I expect the button to turn into a text input and allow editing of the step name

**Comment by bitce** [comment]
Hi @paul-anaplan!

Thanks for the report, we're aware and the fix is already in progress :)
