### ISSUE TITLE
Step item tooltip is a literal "step.displayName()"

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#484]
Reproducible on bitrise.io at the time of writing.

![image](https://user-images.githubusercontent.com/3340954/80235838-81bc4780-865a-11ea-8816-abbe43d06f77.png)

**Comment by bitce** [comment]
I believe it no longer is, but let us know if you still see it!

**Comment by koral--** [comment]
True, it seems to be fixed in the current version.
