### ISSUE TITLE
[!!!] Missing input descriptions

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#51]
Description of inputs is not presented on the UI, but it can be crucial in cases!

E.g.:

![screenshot from 2017-02-13 18-44-49](https://cloud.githubusercontent.com/assets/430618/22895414/a89c195a-f21c-11e6-9f1a-8dbacc7eedb2.png)

https://github.com/bitrise-steplib/steps-create-android-emulator/blob/master/step.yml#L59

**Comment by viktorbenei** [comment]
Pretty please, this is quite important!!

**Comment by erosdome** [comment]
added:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-0-released/1709
