### ISSUE TITLE
Cannot update workflow-editor

### ISSUE THREAD

**Issue by guness** [bitrise-io/bitrise-workflow-editor#517]
I am also confused by logs, what is the latest version so I cannot update plugin by `bitrise plugin update workflow-editor` on my local computer.

here is the logs:

```
Updating plugin workflow-editor
Installing new version (1.3.37)
installed plugin found with version (1.3.12), overriding it...
Plugin update failed, error: failed to install plugin from (https://github.com/bitrise-io/bitrise-workflow-editor.git), error: failed to download plugin executable from (https://github.com/bitrise-io/bitrise-workflow-editor/releases/download/1.3.38/workflow-editor-Darwin-x86_64), error: non success status code (404)

```

it is printing `1.3.37` but trying to install `1.3.38`.

**Comment by bitce** [comment]
Thanks for the report, the team was made aware and we're looking at this!

**Comment by Ozonid** [comment]
Hey @guness !
Sorry for the inconvenience, it should be working now

**Comment by guness** [comment]
yeah, it works now. thanks 👍
