### ISSUE TITLE
Add before/after workflow, UX improvement

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#53]
From the UI it's not clear that I have to select from a drop down, to add a before/after workflow. After clicking the __Add Workflow before__ button in the top bar, I get a popup:

![screenshot from 2017-02-13 18-52-53](https://cloud.githubusercontent.com/assets/430618/22895681/af39bee2-f21d-11e6-89ad-5116c6ff5e27.png)

Once you add the first one it gets a bit better, but still not obvious enough:

![screenshot from 2017-02-13 18-54-14](https://cloud.githubusercontent.com/assets/430618/22895731/d5377648-f21d-11e6-8a19-1deb40b169ab.png)

**Comment by viktorbenei** [comment]
Actually, what if we'd move the __Add Workflow before__ and __Add Workflow after__ buttons right into the workflow chain? Before the very first step there would be a __Add Workflow before__ button, and after the last one a __Add Workflow after__ button

**Comment by viktorbenei** [comment]
@bloodrabbit WDYT?

**Comment by bloodrabbit** [comment]
Closing, will be addressed in a design revision of the whole editor.
