### ISSUE TITLE
Present the version number of the workflow editor somewhere on the UI, for debug

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#54]
For easier bug report, or in case we send a screenshot etc.

**Comment by erosdome** [comment]
placed in the footer right corner?

**Comment by viktorbenei** [comment]
+1

**Comment by erosdome** [comment]
updated:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-4-released/1765
