### ISSUE TITLE
Mark steps where an update is available

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#56]
Similar to the "v1" workflow editor on bitrise.io, mark the steps in the workflow where an update is available.

Also, __clicking the "update available" icon should upgrade the step version to the latest version__.

Bitrise.io "v1" editor:

![screenshot from 2017-02-14 11-14-24](https://cloud.githubusercontent.com/assets/430618/22924843/f14069e2-f2a6-11e6-9c6f-f7f2e4c342d8.png)

Current workflow editor UI:

![screenshot from 2017-02-14 11-14-58](https://cloud.githubusercontent.com/assets/430618/22924854/fa6006fe-f2a6-11e6-8ac9-f16db09e3174.png)

**Comment by erosdome** [comment]
Implemented in new release:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-9-released/1638
