### ISSUE TITLE
Step version change / upgrade: print warning if an input was removed

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#62]
It's enough to print a warning if an input was removed _where the user did specify a value_. If an input was removed in a new version/update of the step but the user did not set any value for it / the value was the default one, there's no need to print a warning.

In the bitrise.io workflow editor this looks like this right now:

1. Click on "Upgrade" for a step, where upgrade is available
1. If an input where I specified a value before is removed by the upgrade:

![screenshot from 2017-02-17 12-01-57](https://cloud.githubusercontent.com/assets/430618/23063145/48e65cd8-f509-11e6-8297-45d74a1b5bf9.png)

I'd personally have two buttons here, one to "accept/OK" and one to "cancel" and don't upgrade to the new version. The current bitrise.io warning is OK, but to cancel you have to click "discard" right now, which is not the best (especially if you changed other things before the step upgrade)

**Comment by erosdome** [comment]
feature added:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-7-released/1335
