### ISSUE TITLE
Multiple instances running

### ISSUE THREAD

**Issue by everlof** [bitrise-io/bitrise-workflow-editor#64]
I'd like to be able to edit different .ymls simultaneously.

As of now, the ports are clutching.

**Comment by viktorbenei** [comment]
Related feature request / discussion: https://discuss.bitrise.io/t/multiple-local-workflow-editors-open/870

**Comment by erosdome** [comment]
added in 1.0.5, will be available shortly on the website too:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-5-released/1790
