### ISSUE TITLE
Failed to load workflows.

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/bitrise-workflow-editor#65]
I installed the latest version of bitrise cli & the workflow editor plugin. I created a folder with `bitrise.yml`. The workflow editor is failing to load the workflow. Am I doing something wrong?

<img width="593" alt="failed_to_load_workflow" src="https://cloud.githubusercontent.com/assets/1173057/23589430/e6fa9de2-019a-11e7-8d87-43a277077da2.png">

- https://gist.github.com/bootstraponline/01c50f24ecd7f971bf6394e1699abc99

```
$ bitrise version
1.5.4
$ go version
go version go1.8 darwin/amd64
$ bitrise :workflow-editor version
0.9.6
```

```
$ bitrise :workflow-editor
Starting API server at http://localhost:3645
Open workflow editor in browser ...
 => GET: /api/bitrise-yml.json - 10.065492ms ()
empty output data
```

```javascript
		}, function(error) {
			viewModel.workflows = undefined;
			console.log(error.message);
			viewModel.configureWorkflowsProgress.error(new Error("Failed to load workflows."));
		});
```

```
POST http://localhost:3645/api/spec 400 (Bad Request)
(anonymous) @ VM228:2
(anonymous) @ main.js:23338
sendReq @ main.js:23131
serverRequest @ main.js:22841
processQueue @ main.js:27448
(anonymous) @ main.js:27464
$eval @ main.js:28716
$digest @ main.js:28532
$apply @ main.js:28824
done @ main.js:23162
completeRequest @ main.js:23360
requestLoaded @ main.js:23301
main.js:57271 Error loading library
```

**Comment by bootstraponline** [comment]
looks like the same issue as https://github.com/bitrise-io/bitrise-workflow-editor/issues/39 😭

**Comment by bootstraponline** [comment]
closing as a dupe

**Comment by bootstraponline** [comment]
seems to be a unique issue, reopening.

**Comment by viktorbenei** [comment]
Did you run any `bitrise run ..` on your Mac?

**Comment by bootstraponline** [comment]
I don't think so. maybe a long time ago

**Comment by viktorbenei** [comment]
Error comes from here: https://github.com/bitrise-io/bitrise-workflow-editor/blob/23d73ccda3793c30420cbd14312cc30ad1dc7390/apiserver/tools/tools.go#L36

What's the output if you run:

```
bitrise "stepman" "collections" "--format" "json"
```

**Comment by bootstraponline** [comment]
```
$ bitrise "stepman" "collections" "--format" "json"
{"steplibs":[{"uri":"https://github.com/bitrise-io/bitrise-steplib.git"}]}
```

**Comment by viktorbenei** [comment]
Please run: `bitrise setup` - I think you have an older version of `stepman`, which is auto updated when you `bitrise run ..` or `bitrise setup`.

**Comment by viktorbenei** [comment]
For ref. my output for the same command:

```
$ bitrise "stepman" "collections" "--format" "json"
{"data":[{"uri":"https://github.com/bitrise-io/bitrise-steplib.git","spec_path":"/Users/viktorbenei/.stepman/step_collections/1486141994/spec/spec.json"}]}
```

The output should include a root `data` element with the latest `stepman` version.

**Comment by bootstraponline** [comment]
I think you're right re: older stepman.

> Installed stepman found, but not a supported version: 0.9.22


after running `bitrise setup` it works now. I think the readme should mention this command.

**Comment by viktorbenei** [comment]
Actually I think this should be enforced, you should not have to run `bitrise setup` manually - I'll reopen this issue here for tracking.

**Comment by viktorbenei** [comment]
E.g. `bitrise run ..` does have built in check for whether `bitrise setup` was performed for the current version and does perform `bitrise setup` automatically if it was not - I'd say this should be the case here too.

**Comment by bootstraponline** [comment]
> I'd say this should be the case here too.

sounds good to me.

**Comment by viktorbenei** [comment]
Added to the CLI issue tracker, hopefully we can ship a solution in the next CLI (will be released in ~1.5 weeks)

**Comment by godrei** [comment]
Hi @bootstraponline ,

the next cli release will be shipped (tomorrow), with auto setup (if needed) in case of running plugins (like the workflow-editor).

Related PR: https://github.com/bitrise-io/bitrise/pull/477

**Comment by bootstraponline** [comment]
nice
