### ISSUE TITLE
Adding a new Triggers item -> remove the default/placeholder "*" from the input!

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#68]
Cliked on Triggers, then on `+ Add Trigger`, started to type in `dep` but got `*dep`

![screenshot from 2017-03-28 11-39-58](https://cloud.githubusercontent.com/assets/430618/24398917/6241be3c-13ab-11e7-92b4-56a284f298b9.png)

**Comment by viktorbenei** [comment]
Not a "bug bug" but I'd consider this to be a UX bug ;)

**Comment by erosdome** [comment]
Fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-9-released/1638
