### ISSUE TITLE
[Feature] Add run_if in workflow editor

### ISSUE THREAD

**Issue by Nikoloutsos** [bitrise-io/bitrise-workflow-editor#692]
As a user I want to skip a certain step.
It would be really nice if run_if was supported as a field in the workflow editor step. IIRC at this time it is supported only in .yml file.

![CleanShot 2022-09-06 at 13 29 10](https://user-images.githubusercontent.com/14034942/188613028-c9b1c479-6419-4ccd-a8b1-44ac7caad3fc.png)

**Comment by morbalint** [comment]
It's implemented by #764 and currently in internal beta testing.
