### ISSUE TITLE
Adding a step available only when editing a current one

### ISSUE THREAD

**Issue by juliengdt** [bitrise-io/bitrise-workflow-editor#81]
Hello,

I am not able to add another step in a current workflow unless i edit one

![before](https://cloud.githubusercontent.com/assets/6575155/24747553/0551767c-1abd-11e7-83ed-ef4b90fbd37a.png)
![after](https://cloud.githubusercontent.com/assets/6575155/24747552/054f4df2-1abd-11e7-90a9-c258ecf290b6.png)

* MacOS 10.12.3
* Safari 10.0.3 (12602.4.8)

**Comment by viktorbenei** [comment]
Huge +1 from me - @bloodrabbit & @erosdome please discuss this as well, as part of the design changes!

**Comment by hijklmno** [comment]
Had me confused as well; had to click around to find where to add a new step.

**Comment by erosdome** [comment]
From the new release, the main workflow of the chain is selected initially, thus initially showing the step add buttons:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-9-released/1638
