### ISSUE TITLE
Insert Variable: the list does not include the workflow specific env vars

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#84]
It should at least include those which are specified for the currently selected workflow, even better would be to include all the workflow env vars specified in the workflow, and through the `before_run` workflows (obviously `after_run` workflows are not available at that point, but `before_run` ones are).

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-10-released/1696
