### ISSUE TITLE
Workflow Editor Button Missing

### ISSUE THREAD

**Issue by giannigdev** [bitrise-io/bitrise-workflow-editor#865]
We have noticed that we can't edit our Pipeline Workflow because the button is missing from the UI. We have tried to change the authorization level both for 'Dev' and 'Admin' but nothing works. This is the current UI we see:

<a href="https://ibb.co/FngcvMc"><img src="https://i.ibb.co/FngcvMc/Screenshot-2024-02-28-at-11-35-33.png" alt="Screenshot-2024-02-28-at-11-35-33" border="0"></a>

**Comment by giannigdev** [comment]
@zoltanszabo-bitrise Are there any updates about this issue?

**Comment by zoltanszabo-bitrise** [comment]
@giannigdev The support team would like to know more about your issue to help you resolve it.
Is there anything you can share with them that might help?

I'd recommend you create a support ticket so they can contact you directly and help you more easily:
https://support.bitrise.io/hc/en-us/requests/new

**Comment by jonnyijapan** [comment]
That button is missing on my page too.
