### ISSUE TITLE
v0.9.9: why the input content is shown at two places when editing?

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#88]
Step input content is shown both in the edit textarea, as well as above that. It's quite confusing, especially with multi line content.
![screenshot from 2017-05-07 18-08-37](https://cloud.githubusercontent.com/assets/430618/25782707/61f9dab2-3350-11e7-9669-f0cb85d46019.png)

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-10-released/1696
