### ISSUE TITLE
BUG: step contents not saved after creating a new empty workflow

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#90]
Steps to reproduce:

1. Create a new workflow, from __Empty__ option
1. Add a Script step
1. Change the script content to anything
1. Save

Switch to bitrise.yml mode or check the yml: the Script step is there in the new workflow, but its content is not!

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-10-released/1696
