### ISSUE TITLE
[!] Output Alias handling - new feature in the new CLI version, which will be released today

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#91]
CLI version most likely will be `1.6.0` - with `format_version: 3`

Alias can be defined for outputs now (format version 3). If an alias is defined for a step's output then that specific output will be exposed with the alias env key instead of the original key!

But, this only applies for that single step. If there's two of that step, one where aliased one where not, then both env keys will exist!

Related integration test: https://github.com/bitrise-io/bitrise/pull/494/files

**Comment by viktorbenei** [comment]
AFAIK this only affects the "Insert Variable" popup. Not sure if affects something else, but definitely affects the insert var popup.

**Comment by viktorbenei** [comment]
Ahh, actually it does affect one more thing: the alias should be editable by the user! ;)

Instead of simply listing the step outputs there should be some kind of "edit" option, to specify an alias env var key.

**Comment by doomsayer13** [comment]
We created a card in our internal report system to fix/implement it, so I'm going to close this ticket.
