### ISSUE TITLE
Step list in the "add step" sidebar is empty if the config does not have any steps

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#94]
Example:

```
format_version: "3"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
workflows:
  test: {}
```

![screen shot 2017-05-09 at 20 17 14](https://cloud.githubusercontent.com/assets/430618/25865816/8d20c8e0-34f4-11e7-8fc9-90dcfb037ff4.png)

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-10-released/1696
