### ISSUE TITLE
prevent asset caching issues on new version releases

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#96]

**Comment by viktorbenei** [comment]
+1

**Comment by erosdome** [comment]
added for website mode:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-3-released/1743

todo: add it for CLI mode as well

**Comment by erosdome** [comment]
added for CLI mode:

https://discuss.bitrise.io/t/workflow-editor-v1-0-10-released/2135
