### ISSUE TITLE
Env Vars - validate the key (as-you-type)

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#97]
There's absolutely no indication that the env var key is invalid, until you try to save it.

![screenshot from 2017-05-11 15-49-28](https://cloud.githubusercontent.com/assets/430618/25952665/9381f92a-3661-11e7-823b-5c0c81c3d171.png)

I'd go with an error message like the one on bitrise.io in file storage:

![screenshot from 2017-05-11 15-53-48](https://cloud.githubusercontent.com/assets/430618/25952875/26723a06-3662-11e7-9632-0a1c1650db96.png)

**Comment by erosdome** [comment]
added:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v1-0-0-released/1709
