### ISSUE TITLE
Adding newline/whitespace to a step input does not trigger "config changed" - can't save it.

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#98]
Repro:

1. add a **Script** step
1. save the workflow - save button should be "gray" / disabled
1. then start to hit Enter in the Script's Content, some space too.. or any whitespace char

You can't save the config change, as the save button is still disabled, unless you type in any non whitespace char

**Comment by erosdome** [comment]
fixed:

https://discuss.bitrise.io/t/workflow-editor-v1-0-9-released/2004
